version: "3"
services:
       api:
           container_name: api
           build: .
           restart: always
           ports:
             - "80:80"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'