version: "3"
services:
       api:
           container_name: api
           build: .
           restart: always
           environment:
            - PORT=80
            - mongo=mongo
           ports:
             - "80:80"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             ports:
               - '27017:27017'